language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  # Dependencies for shiny/rmarkdown integration
  # Thanks RStudio! https://github.com/rstudio/rmarkdown/blob/master/.travis.yml
  # Install binary pandoc from Rstudio
  - mkdir -p $HOME/opt/pandoc
  - curl -O http://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
  - unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc
    -d $HOME/opt/pandoc
  - chmod +x $HOME/opt/pandoc/pandoc*
  - rm pandoc-1.12.3.zip
  - $HOME/opt/pandoc/pandoc --version
  # install uninstalled packages which this pkg depends on/links to/suggests.
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_github jimhester/covr ropensci/RSelenium@22f06b9f2a675015d0daa3318319044e4e60d2fa
  - Rscript -e "devtools::install(dep=FALSE)"

script:
  - if [ "$TEST_SUITE" == "CRAN" ];then bash build.sh;else Rscript -e "source('tests/testthat.R', chdir = TRUE)";fi

after_success:
  - Rscript -e "library(covr);coveralls()"

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - secure: "h06r9Nn7Y01TKEsPy9IWlSj38GopqKcjaNY5pH2/tRfQzNtlmDJKz2R028d5LtVk3tdpen6GTTKwDeWVmQUH63p6BffNjrhmB+JTk+2g4SSx8C8gJqSF0zPEIzz+8012PxXaW/4MIA8l/EJN1Y8ESxsLJNacBJYkWYNYLMCoRZ4="
  matrix:
    - TEST_SUITE=renderer1
    - TEST_SUITE=renderer2
    - TEST_SUITE=renderer3
    - TEST_SUITE=renderer4
    - TEST_SUITE=renderer5
    - TEST_SUITE=compiler
    - TEST_SUITE=CRAN
    
    
